<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MJLT-1563" ignored="0" name="Test" tests="1" failures="1" timestamp="2024-03-26T14:56:07 IST" time="86.102" errors="0">
  <testcase name="createTenderFromPR_Dynamically" time="69.157" classname="com.dynamicity.CreateTenderFromPR_Dynamically">
    <failure type="java.lang.RuntimeException" message="Failed to connect to the database">
      <![CDATA[java.lang.RuntimeException: Failed to connect to the database
at com.Database.DatabaseComponent.DatabaseComponent_New(DatabaseComponent.java:43)
at com.Database.DatabaseComponent.encryptedPWD(DatabaseComponent.java:106)
at com.API.API_Component.Login(API_Component.java:2586)
at com.components.Dynamicity.templateGroupDetails(Dynamicity.java:7665)
at com.dynamicity.CreateTenderFromPR_Dynamically.createTenderFromPR_Dynamically(CreateTenderFromPR_Dynamically.java:54)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- createTenderFromPR_Dynamically -->
</testsuite> <!-- Test -->
