<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MJLT-2170" name="com.testScripts_mjunction.TC_SN_02VerifyEndToEndWorkFlowOfSanctionNoteWithUserdefinedWorkFlowTest" tests="1" failures="1" timestamp="2024-02-14T13:30:55 IST" time="4.263" errors="0">
  <testcase name="f" time="4.263" classname="com.testScripts_mjunction.TC_SN_02VerifyEndToEndWorkFlowOfSanctionNoteWithUserdefinedWorkFlowTest">
    <failure type="java.lang.AssertionError" message="Error Message : Error in launching the application:null value in entry: url=null">
      <![CDATA[java.lang.AssertionError: Error Message : Error in launching the application:null value in entry: url=null
at com.baseClasses.AutomationException.<init>(AutomationException.java:11)
at com.baseClasses.BaseClass_Web.launchapp(BaseClass_Web.java:78)
at com.components.eTenderComponent.openURL(eTenderComponent.java:156)
at com.testScripts_mjunction.TC_SN_02VerifyEndToEndWorkFlowOfSanctionNoteWithUserdefinedWorkFlowTest.f(TC_SN_02VerifyEndToEndWorkFlowOfSanctionNoteWithUserdefinedWorkFlowTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- f -->
  <system-out/>
</testsuite> <!-- com.testScripts_mjunction.TC_SN_02VerifyEndToEndWorkFlowOfSanctionNoteWithUserdefinedWorkFlowTest -->
